version: '2'

services:
  slim_adr_nginx:
    image: nginx:stable
    networks:
      - slim_adr
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/sites.conf:/etc/nginx/conf.d/default.conf

  slim_adr_phpfpm:
    build:
      context: ./docker/phpfpm
    networks:
      - slim_adr
    expose:
      - 9000
    volumes:
      - ./:/var/www/slim_adr
      - ./docker/phpfpm/php.timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./docker/phpfpm/php.error.ini:/usr/local/etc/php/conf.d/error.ini
    working_dir: /var/www/slim_adr

networks:
  slim_adr:
    driver: bridge